# Lab 1: Basic NumPy Operations
- **Student Name:** Ali Cihan Ozdemir
- **Section:** Part A - General NumPy Operations

In [9]:
import numpy as np # Import the core NumPy library

In [10]:
# 2. Create an array starting at 1, ending at 20, incremented by 3
arr1 = np.arange(1, 21, 3)
print("Array 1 (1 to 20, inc 3):\n", arr1)

# 3. Create a new array of shape 3 with random numbers between 0 and 1
rand_arr = np.random.rand(3)
print("\nRandom Array (Shape 3):\n", rand_arr)

Array 1 (1 to 20, inc 3):
 [ 1  4  7 10 13 16 19]

Random Array (Shape 3):
 [0.43421359 0.30051943 0.55908496]


In [11]:
# 4. Create a 2D array
arr2d = np.array([[10, 20, 45],
                  [30, 12, 16],
                  [42, 17, 56]])

# Slice to get the first two rows
first_two = arr2d[:2, :]
# Slice to get the last two rows
last_two = arr2d[1:, :]

print("Original 2D Array:\n", arr2d)
print("\nFirst Two Rows:\n", first_two)
print("Last Two Rows:\n", last_two)

Original 2D Array:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]

First Two Rows:
 [[10 20 45]
 [30 12 16]]
Last Two Rows:
 [[30 12 16]
 [42 17 56]]


In [12]:
# 5. Create two 2x2 arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

v_stack = np.vstack((a, b)) # Vertical stacking
h_stack = np.hstack((a, b)) # Horizontal stacking

# Split the vertical stack back into two smaller arrays
split_arr = np.array_split(v_stack, 2)

print("Vertical Stack:\n", v_stack)
print("\nHorizontal Stack:\n", h_stack)
print("\nSplit Array (First Part):\n", split_arr[0])

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Split Array (First Part):
 [[1 2]
 [3 4]]


In [13]:
# 6. Matrix Multiplication Matrices
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]]) # 3x3
Y = np.array([[4, 2], [6, 2], [4, 2]])          # 3x2

# Multiplication is possible if Columns of X == Rows of Y
print("Is X (3x3) * Y (3x2) possible? Yes.")
res = np.dot(X, Y)
print("Result of X * Y:\n", res)

# Demonstrate the case where it is NOT possible
print("\nAttempting Y (3x2) * X (3x3):")
try:
    fail = np.dot(Y, X)
except ValueError as e:
    print("Multiplication failed as expected:", e)

Is X (3x3) * Y (3x2) possible? Yes.
Result of X * Y:
 [[70 28]
 [70 30]
 [60 26]]

Attempting Y (3x2) * X (3x3):
Multiplication failed as expected: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


In [14]:
# 7. Vectors x and y
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

print(f"Vector x - Shape: {x.shape}, Dimensions: {x.ndim}")

# Reshaping to (3,1)
x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)

print(f"Reshaped x Shape: {x_reshaped.shape}")
print(f"Vector y - Dimensions after reshaping: {y_reshaped.ndim}")

Vector x - Shape: (3,), Dimensions: 1
Reshaped x Shape: (3, 1)
Vector y - Dimensions after reshaping: 2


In [15]:
# 8. Broadcasting Demonstration
# Broadcasting allows NumPy to perform operations on arrays of different shapes.
c1_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 3x3 matrix

# Subtraction (Matrix - Scalar)
sub_res = c1_matrix - 4
# Multiplication (Matrix * Scalar)
mul_res = c1_matrix * 2

print("Original 3x3 Matrix:\n", c1_matrix)
print("\nSubtraction (Matrix - 4):\n", sub_res)
print("Multiplication (Matrix * 2):\n", mul_res)

Original 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtraction (Matrix - 4):
 [[-3 -2 -1]
 [ 0  1  2]
 [ 3  4  5]]
Multiplication (Matrix * 2):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Operation Overviews
- **Array Creation:** Successfully generated sequenced and random numerical arrays using `arange` and `random`.
- **Slicing:** Extracted specific sub-sections of a 2D matrix using coordinate indexing.
- **Stacking/Splitting:** Combined multiple arrays into larger structures and partitioned them back into segments.
- **Matrix Logic:** Validated the mathematical rules for dot product compatibility between different shapes.
- **Dimensions:** Observed how reshaping a vector into a matrix increases its dimensionality from 1 to 2.
- **Broadcasting:** Demonstrated pointwise arithmetic where a scalar value is "broadcast" across a larger matrix.

In [16]:
# Part B: Linear Equations
print("--- System 1 ---")
# 2x1 + 3x2 - 4x3 = 6
# 1x1 - 4x2 + 0x3 = 8
A1 = np.array([[2, 3, -4], [1, -4, 0]])
B1 = np.array([6, 8])

# Determine number of solutions via Rank
rank_A1 = np.linalg.matrix_rank(A1)
print(f"Rank of A1: {rank_A1}")
print("Number of unknowns (3) > Rank (2). Thus, there are infinitely many solutions.")

# System 2
print("\n--- System 2 ---")
# 3y1 - 4y2 + 5y3 = 10
# -1y1 + 2y2 - 4y3 = 8
A2 = np.array([[3, -4, 5], [-1, 2, -4]])
B2 = np.array([10, 8])

rank_A2 = np.linalg.matrix_rank(A2)
print(f"Rank of A2: {rank_A2}")
print("Number of unknowns (3) > Rank (2). Thus, there are infinitely many solutions.")

# Finding a sample solution using least-squares (as done in lecturer's files)
sol1 = np.linalg.lstsq(A1, B1, rcond=None)[0]
sol2 = np.linalg.lstsq(A2, B2, rcond=None)[0]
print("\nSample solution for System 1:", sol1)
print("Sample solution for System 2:", sol2)

--- System 1 ---
Rank of A1: 2
Number of unknowns (3) > Rank (2). Thus, there are infinitely many solutions.

--- System 2 ---
Rank of A2: 2
Number of unknowns (3) > Rank (2). Thus, there are infinitely many solutions.

Sample solution for System 1: [ 1.6692112 -1.5826972 -1.8524173]
Sample solution for System 2: [ 7.46067416 -4.62921348 -6.17977528]
